const bcrypt = require('bcryptjs');
const { v4: uuidv4 } = require('uuid');
const { pool } = require('../config/db');
const { createAndSendPasswordToken } = require('./authController');
const { createNotification } = require('./notificationController');
const { logAudit } = require('../utils/audit');
const { sendSuperDistributorCreatedEmail, sendDistributorCreatedEmail } = require('../utils/email');
const { stripSchoolBlobFields } = require('../utils/stripBlobFields');

// ===================== SUPER ADMIN SIDE =====================

async function listSuperDistributors(req, res) {
  try {
    const [rows] = await pool.query(
      `SELECT u.id, u.name, u.email, u.mobile, u.is_active, u.created_at,
              sd.district, sd.city, sd.address, sd.area_of_operation, sd.commission_rate,
              sd.avatar_url, sd.pan_number, sd.bank_account_holder, sd.bank_name, sd.bank_account_number, sd.bank_ifsc,
              (SELECT COUNT(*) FROM distributors d WHERE d.super_distributor_id = u.id AND d.deleted_at IS NULL) as distributor_count,
              (SELECT COUNT(*) FROM schools s WHERE s.super_distributor_id = u.id AND s.deleted_at IS NULL) as direct_school_count
       FROM users u
       LEFT JOIN distributors sd ON sd.user_id = u.id
       WHERE u.role = 'superDistributor' AND u.deleted_at IS NULL
       ORDER BY u.created_at DESC`
    );
    res.json({ superDistributors: rows });
  } catch (err) {
    console.error('listSuperDistributors error:', err.message);
    res.status(500).json({ error: 'Server error fetching super distributors' });
  }
}

async function createSuperDistributor(req, res) {
  const conn = await pool.getConnection();
  try {
    const { name, email, mobile, city, district, address, area_of_operation, commission_rate, password, confirmPassword,
            pan_number, bank_account_holder, bank_name, bank_account_number, bank_ifsc } = req.body;
    if (!name || !email) return res.status(400).json({ error: 'Name and email are required' });
    if (!district) return res.status(400).json({ error: 'District is required' });

    if (password !== undefined && password !== '') {
      if (password.length < 8) return res.status(400).json({ error: 'Password must be at least 8 characters' });
      if (confirmPassword !== undefined && password !== confirmPassword) {
        return res.status(400).json({ error: 'Password and confirm password do not match' });
      }
    }

    const [existing] = await conn.query('SELECT id FROM users WHERE email = ? AND deleted_at IS NULL', [email.toLowerCase().trim()]);
    if (existing.length > 0) return res.status(409).json({ error: 'A user with this email already exists' });

    await conn.beginTransaction();

    const userId = uuidv4();
    const hasPassword = Boolean(password);
    const passwordHash = hasPassword ? await bcrypt.hash(password, 10) : null;

    await conn.query(
      `INSERT INTO users (id, role, name, email, mobile, password_hash, is_active, password_set, created_by) VALUES (?, 'superDistributor', ?, ?, ?, ?, 1, ?, ?)`,
      [userId, name, email.toLowerCase().trim(), mobile || null, passwordHash, hasPassword ? 1 : 0, req.user.id]
    );

    // Store SD profile in distributors table (reusing same table, with super_distributor_id = NULL).
    // commission_rate here is the SD's own flat commission — a % of the price
    // of every certificate generated by schools under this SD's hierarchy —
    // separate from (and in addition to) the School/Platform split engine.
    // Defaults to 2%, matching the business rule; Super Admin can override.
    const sdId = uuidv4();
    await conn.query(
      `INSERT INTO distributors (id, user_id, commission_rate, city, district, address, area_of_operation,
                                  pan_number, bank_account_holder, bank_name, bank_account_number, bank_ifsc)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [sdId, userId, commission_rate !== undefined && commission_rate !== '' ? commission_rate : 2.0, city || null, district, address || null, area_of_operation || null,
       pan_number || null, bank_account_holder || null, bank_name || null, bank_account_number || null, bank_ifsc || null]
    );

    await conn.commit();

    let message;
    if (hasPassword) {
      message = 'Super Distributor created. They can log in immediately.';
      sendSuperDistributorCreatedEmail(email, name, {
        username: email.toLowerCase().trim(),
        password,
        loginUrl: req.headers.origin,
        relatedUserId: userId,
      }).catch(e => console.error('SD welcome email failed:', e.message));
    } else {
      const emailResult = await createAndSendPasswordToken(
        { id: userId, name, email, role: 'superDistributor' },
        'setup',
        req.headers.origin,
        { role: 'superDistributor', username: email.toLowerCase().trim() }
      );
      if (!emailResult.success) console.error('SD setup email failed:', emailResult.error);
      message = 'Super Distributor created. Password setup email sent.';
    }

    const [rows] = await pool.query(
       `SELECT u.id, u.name, u.email, u.mobile, u.is_active, d.district, d.city, d.address, d.area_of_operation,
               d.commission_rate, d.avatar_url, d.pan_number, d.bank_account_holder, d.bank_name, d.bank_account_number, d.bank_ifsc
       FROM users u LEFT JOIN distributors d ON d.user_id = u.id WHERE u.id = ?`,
      [userId]
    );
    res.status(201).json({ superDistributor: rows[0], message });
  } catch (err) {
    await conn.rollback();
    console.error('createSuperDistributor error:', err.message);
    res.status(500).json({ error: 'Server error creating super distributor' });
  } finally {
    conn.release();
  }
}

async function updateSuperDistributorByAdmin(req, res) {
  try {
    const { id } = req.params;
    const { name, mobile, city, district, address, area_of_operation, commission_rate, is_active,
            pan_number, bank_account_holder, bank_name, bank_account_number, bank_ifsc } = req.body;

    const [userRows] = await pool.query("SELECT id FROM users WHERE id = ? AND role = 'superDistributor' AND deleted_at IS NULL", [id]);
    if (userRows.length === 0) return res.status(404).json({ error: 'Super distributor not found' });

    if (name !== undefined) await pool.query('UPDATE users SET name = ? WHERE id = ?', [name, id]);
    if (mobile !== undefined) await pool.query('UPDATE users SET mobile = ? WHERE id = ?', [mobile, id]);
    if (is_active !== undefined) await pool.query('UPDATE users SET is_active = ? WHERE id = ?', [is_active ? 1 : 0, id]);

    const updates = [];
    const values = [];
    if (city !== undefined) { updates.push('city = ?'); values.push(city); }
    if (district !== undefined) { updates.push('district = ?'); values.push(district); }
    if (address !== undefined) { updates.push('address = ?'); values.push(address); }
    if (area_of_operation !== undefined) { updates.push('area_of_operation = ?'); values.push(area_of_operation); }
    if (commission_rate !== undefined) { updates.push('commission_rate = ?'); values.push(commission_rate); }
    if (pan_number !== undefined) { updates.push('pan_number = ?'); values.push(pan_number); }
    if (bank_account_holder !== undefined) { updates.push('bank_account_holder = ?'); values.push(bank_account_holder); }
    if (bank_name !== undefined) { updates.push('bank_name = ?'); values.push(bank_name); }
    if (bank_account_number !== undefined) { updates.push('bank_account_number = ?'); values.push(bank_account_number); }
    if (bank_ifsc !== undefined) { updates.push('bank_ifsc = ?'); values.push(bank_ifsc); }
    if (updates.length > 0) {
      values.push(id);
      await pool.query(`UPDATE distributors SET ${updates.join(', ')} WHERE user_id = ?`, values);
    }

    const [rows] = await pool.query(
        `SELECT u.id, u.name, u.email, u.mobile, u.is_active, d.district, d.city, d.address, d.area_of_operation, d.commission_rate,
                d.avatar_url, d.pan_number, d.bank_account_holder, d.bank_name, d.bank_account_number, d.bank_ifsc
       FROM users u LEFT JOIN distributors d ON d.user_id = u.id WHERE u.id = ?`,
      [id]
    );
    res.json({ superDistributor: rows[0] });
  } catch (err) {
    console.error('updateSuperDistributorByAdmin error:', err.message);
    res.status(500).json({ error: 'Server error updating super distributor' });
  }
}

// PUT /api/super-distributors/:id/avatar (superAdmin) - photo upload for a
// super distributor from the admin's own Edit modal.
async function uploadSuperDistributorAvatarByAdmin(req, res) {
  try {
    if (!req.file) return res.status(400).json({ error: 'No image file provided' });
    const [rows] = await pool.query("SELECT id FROM users WHERE id = ? AND role = 'superDistributor' AND deleted_at IS NULL", [req.params.id]);
    if (rows.length === 0) return res.status(404).json({ error: 'Super distributor not found' });
    const avatarUrl = req.file.path;
    await pool.query('UPDATE distributors SET avatar_url = ? WHERE user_id = ?', [avatarUrl, req.params.id]);
    res.json({ avatar_url: avatarUrl });
  } catch (err) {
    console.error('uploadSuperDistributorAvatarByAdmin error:', err.message);
    res.status(500).json({ error: 'Server error uploading profile photo' });
  }
}

async function deleteSuperDistributor(req, res) {
  try {
    const { id } = req.params;
    const [rows] = await pool.query("SELECT id FROM users WHERE id = ? AND role = 'superDistributor' AND deleted_at IS NULL", [id]);
    if (rows.length === 0) return res.status(404).json({ error: 'Super distributor not found' });

    await pool.query('UPDATE users SET deleted_at = NOW(), is_active = 0 WHERE id = ?', [id]);
    await pool.query('UPDATE distributors SET deleted_at = NOW() WHERE user_id = ?', [id]);

    res.json({ message: 'Super distributor deactivated successfully' });
  } catch (err) {
    console.error('deleteSuperDistributor error:', err.message);
    res.status(500).json({ error: 'Server error deleting super distributor' });
  }
}

// ===================== SUPER DISTRIBUTOR'S OWN SIDE =====================

// Helper: verify school/distributor belongs to this SD
async function isMyDistributor(sdUserId, distributorId) {
  const [rows] = await pool.query(
    'SELECT id FROM distributors WHERE id = ? AND super_distributor_id = ? AND deleted_at IS NULL',
    [distributorId, sdUserId]
  );
  return rows.length > 0;
}

async function isMySchool(sdUserId, schoolId) {
  const [rows] = await pool.query(
    `SELECT s.id FROM schools s
     LEFT JOIN distributors d ON d.id = s.distributor_id
     WHERE s.id = ? AND s.deleted_at IS NULL
       AND (s.super_distributor_id = ? OR d.super_distributor_id = ?)`,
    [schoolId, sdUserId, sdUserId]
  );
  return rows.length > 0;
}

async function getMyProfile(req, res) {
  try {
    const [rows] = await pool.query(
        `SELECT u.id, u.name, u.email, u.mobile, d.district, d.city, d.address, d.area_of_operation,
                d.avatar_url, d.commission_rate, d.pan_number, d.bank_account_holder, d.bank_name,
                d.bank_account_number, d.bank_ifsc
       FROM users u LEFT JOIN distributors d ON d.user_id = u.id WHERE u.id = ?`,
      [req.user.id]
    );
    if (rows.length === 0) return res.status(404).json({ error: 'Profile not found' });
    res.json({ profile: rows[0] });
  } catch (err) {
    console.error('SD getMyProfile error:', err.message);
    res.status(500).json({ error: 'Server error fetching profile' });
  }
}

async function updateMyProfile(req, res) {
  try {
    const { name, mobile, city, district, address, area_of_operation, pan_number,
            bank_account_holder, bank_name, bank_account_number, bank_ifsc } = req.body;
    if (name !== undefined) await pool.query('UPDATE users SET name = ? WHERE id = ?', [name, req.user.id]);
    if (mobile !== undefined) await pool.query('UPDATE users SET mobile = ? WHERE id = ?', [mobile, req.user.id]);

    const updates = [];
    const values = [];
    if (city !== undefined) { updates.push('city = ?'); values.push(city); }
    if (district !== undefined) { updates.push('district = ?'); values.push(district); }
    if (address !== undefined) { updates.push('address = ?'); values.push(address); }
    if (area_of_operation !== undefined) { updates.push('area_of_operation = ?'); values.push(area_of_operation); }
    if (pan_number !== undefined) { updates.push('pan_number = ?'); values.push(pan_number); }
    if (bank_account_holder !== undefined) { updates.push('bank_account_holder = ?'); values.push(bank_account_holder); }
    if (bank_name !== undefined) { updates.push('bank_name = ?'); values.push(bank_name); }
    if (bank_account_number !== undefined) { updates.push('bank_account_number = ?'); values.push(bank_account_number); }
    if (bank_ifsc !== undefined) { updates.push('bank_ifsc = ?'); values.push(bank_ifsc); }
    if (updates.length > 0) {
      values.push(req.user.id);
      await pool.query(`UPDATE distributors SET ${updates.join(', ')} WHERE user_id = ?`, values);
    }

    const [rows] = await pool.query(
      `SELECT u.id, u.name, u.email, u.mobile, d.district, d.city, d.address, d.area_of_operation,
              d.avatar_url, d.commission_rate, d.pan_number, d.bank_account_holder, d.bank_name,
              d.bank_account_number, d.bank_ifsc
       FROM users u LEFT JOIN distributors d ON d.user_id = u.id WHERE u.id = ?`,
      [req.user.id]
    );
    res.json({ profile: rows[0] });
  } catch (err) {
    console.error('SD updateMyProfile error:', err.message);
    res.status(500).json({ error: 'Server error updating profile' });
  }
}

// PUT /api/super-distributors/me/avatar - profile photo upload
async function uploadMyAvatar(req, res) {
  try {
    if (!req.file) return res.status(400).json({ error: 'No image file provided' });
    const avatarUrl = req.file.path;
    await pool.query('UPDATE distributors SET avatar_url = ? WHERE user_id = ?', [avatarUrl, req.user.id]);
    res.json({ avatar_url: avatarUrl });
  } catch (err) {
    console.error('SD uploadMyAvatar error:', err.message);
    res.status(500).json({ error: 'Server error uploading profile photo' });
  }
}

async function changeMyPassword(req, res) {
  try {
    const { currentPassword, newPassword } = req.body;
    if (!currentPassword || !newPassword) return res.status(400).json({ error: 'Current and new password are required' });
    if (newPassword.length < 8) return res.status(400).json({ error: 'New password must be at least 8 characters' });

    const [rows] = await pool.query('SELECT password_hash FROM users WHERE id = ?', [req.user.id]);
    const valid = await bcrypt.compare(currentPassword, rows[0]?.password_hash || '');
    if (!valid) return res.status(401).json({ error: 'Current password is incorrect' });

    const hash = await bcrypt.hash(newPassword, 10);
    await pool.query('UPDATE users SET password_hash = ?, password_set = 1 WHERE id = ?', [hash, req.user.id]);
    await logAudit({ userId: req.user.id, action: 'PASSWORD_CHANGED', ipAddress: req.ip });
    res.json({ message: 'Password changed successfully' });
  } catch (err) {
    console.error('SD changeMyPassword error:', err.message);
    res.status(500).json({ error: 'Server error changing password' });
  }
}

// GET /api/super-distributors/me/dashboard
async function getDashboard(req, res) {
  try {
    const sdId = req.user.id;

    // Total distributors under this SD
    const [distCount] = await pool.query(
      'SELECT COUNT(*) as c FROM distributors WHERE super_distributor_id = ? AND deleted_at IS NULL',
      [sdId]
    );

    // Total schools (direct + via distributors)
    const [schoolCount] = await pool.query(
      `SELECT COUNT(*) as c FROM schools s
       LEFT JOIN distributors d ON d.id = s.distributor_id
       WHERE s.deleted_at IS NULL
         AND (s.super_distributor_id = ? OR d.super_distributor_id = ?)`,
      [sdId, sdId]
    );

    // Pending schools
    const [pendingCount] = await pool.query(
      `SELECT COUNT(*) as c FROM schools s
       LEFT JOIN distributors d ON d.id = s.distributor_id
       WHERE s.deleted_at IS NULL AND s.status = 'pending'
         AND (s.super_distributor_id = ? OR d.super_distributor_id = ?)`,
      [sdId, sdId]
    );

    // Revenue: sum of certificate prices from schools under this SD
    const [revenueRows] = await pool.query(
      `SELECT COALESCE(SUM(c.price), 0) as total
       FROM certificates c
       JOIN schools s ON s.id = c.school_id
       LEFT JOIN distributors d ON d.id = s.distributor_id
       WHERE s.deleted_at IS NULL
         AND (s.super_distributor_id = ? OR d.super_distributor_id = ?)`,
      [sdId, sdId]
    );

    // Recently added schools
    const [recentSchools] = await pool.query(
      `SELECT s.id, s.name, s.status, s.created_at,
              u_admin.name as admin_name,
              du.name as distributor_name, du.mobile as distributor_phone
       FROM schools s
       LEFT JOIN users u_admin ON u_admin.id = s.admin_user_id
       LEFT JOIN distributors d ON d.id = s.distributor_id
       LEFT JOIN users du ON du.id = d.user_id
       WHERE s.deleted_at IS NULL
         AND (s.super_distributor_id = ? OR d.super_distributor_id = ?)
       ORDER BY s.created_at DESC LIMIT 10`,
      [sdId, sdId]
    );

    // Actual earnings — from the commission ledger's permanent snapshot,
    // never recalculated from today's percentages. commission_ledger stores
    // super_distributor_id directly, so no school/distributor join is needed.
    const [[earnings]] = await pool.query(
      `SELECT COALESCE(SUM(super_distributor_amount),0) as total,
              COALESCE(SUM(CASE WHEN DATE(created_at)=CURDATE() THEN super_distributor_amount ELSE 0 END),0) as today,
              COALESCE(SUM(CASE WHEN YEAR(created_at)=YEAR(CURDATE()) AND MONTH(created_at)=MONTH(CURDATE()) THEN super_distributor_amount ELSE 0 END),0) as this_month,
              COUNT(*) as total_certificates
       FROM commission_ledger WHERE super_distributor_id = ? AND status='confirmed'`,
      [sdId]
    );
    const [byType] = await pool.query(
      `SELECT certificate_type, COALESCE(SUM(super_distributor_amount),0) as total, COUNT(*) as count
       FROM commission_ledger WHERE super_distributor_id = ? AND status='confirmed' GROUP BY certificate_type`,
      [sdId]
    );
    const [byDistributor] = await pool.query(
      `SELECT d.id as distributor_id, u.name as distributor_name, COALESCE(SUM(cl.super_distributor_amount),0) as total
       FROM commission_ledger cl
       JOIN distributors d ON d.id = cl.distributor_id
       JOIN users u ON u.id = d.user_id
       WHERE cl.super_distributor_id = ? AND cl.status='confirmed'
       GROUP BY d.id, u.name ORDER BY total DESC`,
      [sdId]
    );

    // Flat SD commission — this SD's own commission_rate (%) applied to the
    // price of every certificate generated under this SD's hierarchy.
    // Separate from, and additional to, the commission_ledger split above.
    const [[sdProfile]] = await pool.query(
      `SELECT commission_rate FROM distributors WHERE user_id = ? AND super_distributor_id IS NULL AND deleted_at IS NULL LIMIT 1`,
      [sdId]
    );
    const flatRate = sdProfile ? Number(sdProfile.commission_rate) || 0 : 0;
    const [flatByMonth] = await pool.query(
      `SELECT DATE_FORMAT(c.created_at, '%Y-%m') as month, COALESCE(SUM(c.price),0) as certTotal, COUNT(*) as count
       FROM certificates c
       JOIN schools s ON s.id = c.school_id
       LEFT JOIN distributors d ON d.id = s.distributor_id
       WHERE s.deleted_at IS NULL
         AND (s.super_distributor_id = ? OR d.super_distributor_id = ?)
         AND c.created_at >= DATE_SUB(CURDATE(), INTERVAL 6 MONTH)
       GROUP BY month ORDER BY month ASC`,
      [sdId, sdId]
    );
    const flatCommission = {
      rate: flatRate,
      total: Number((Number(revenueRows[0].total) * flatRate / 100).toFixed(2)),
      byMonth: flatByMonth.map(r => ({
        month: r.month,
        certificateTotal: Number(r.certTotal),
        commission: Number((Number(r.certTotal) * flatRate / 100).toFixed(2)),
        count: Number(r.count),
      })),
    };

    res.json({
      totalDistributors: Number(distCount[0].c),
      totalSchools: Number(schoolCount[0].c),
      pendingSchools: Number(pendingCount[0].c),
      revenue: Number(revenueRows[0].total),
      recentSchools,
      earnings: {
        total: Number(earnings.total),
        today: Number(earnings.today),
        thisMonth: Number(earnings.this_month),
        totalCertificates: Number(earnings.total_certificates),
        byCertificateType: byType.map(r => ({ type: r.certificate_type, total: Number(r.total), count: Number(r.count) })),
        byDistributor: byDistributor.map(r => ({ distributorId: r.distributor_id, name: r.distributor_name, total: Number(r.total) })),
      },
      flatCommission,
    });
  } catch (err) {
    console.error('SD getDashboard error:', err.message);
    res.status(500).json({ error: 'Server error fetching dashboard' });
  }
}

// GET /api/super-distributors/me/distributors
async function listMyDistributors(req, res) {
  try {
    const [rows] = await pool.query(
      `SELECT d.id, d.commission_rate, d.city, d.district, d.address, d.area_of_operation, d.avatar_url,
              d.pan_number, d.bank_account_holder, d.bank_name, d.bank_account_number, d.bank_ifsc, d.created_at,
              u.name, u.email, u.mobile, u.is_active,
              (SELECT COUNT(*) FROM schools s WHERE s.distributor_id = d.id AND s.deleted_at IS NULL) as school_count
       FROM distributors d JOIN users u ON u.id = d.user_id
       WHERE d.super_distributor_id = ? AND d.deleted_at IS NULL
       ORDER BY u.created_at DESC`,
      [req.user.id]
    );
    res.json({ distributors: rows });
  } catch (err) {
    console.error('SD listMyDistributors error:', err.message);
    res.status(500).json({ error: 'Server error fetching distributors' });
  }
}

// POST /api/super-distributors/me/distributors
async function createMyDistributor(req, res) {
  const conn = await pool.getConnection();
  try {
    const { name, email, mobile, city, district, address, area_of_operation, commission_rate, password, confirmPassword,
            pan_number, bank_account_holder, bank_name, bank_account_number, bank_ifsc } = req.body;
    if (!name || !email) return res.status(400).json({ error: 'Name and email are required' });

    if (password !== undefined && password !== '') {
      if (password.length < 8) return res.status(400).json({ error: 'Password must be at least 8 characters' });
      if (confirmPassword !== undefined && password !== confirmPassword) {
        return res.status(400).json({ error: 'Passwords do not match' });
      }
    }

    const [existing] = await conn.query('SELECT id FROM users WHERE email = ? AND deleted_at IS NULL', [email.toLowerCase().trim()]);
    if (existing.length > 0) return res.status(409).json({ error: 'A user with this email already exists' });

    // Get SD's own district to inherit if not specified
    const [sdRows] = await conn.query('SELECT district FROM distributors WHERE user_id = ?', [req.user.id]);
    const sdDistrict = sdRows[0]?.district || null;

    await conn.beginTransaction();

    const userId = uuidv4();
    const hasPassword = Boolean(password);
    const passwordHash = hasPassword ? await bcrypt.hash(password, 10) : null;

    await conn.query(
      `INSERT INTO users (id, role, name, email, mobile, password_hash, is_active, password_set, created_by) VALUES (?, 'distributor', ?, ?, ?, ?, 1, ?, ?)`,
      [userId, name, email.toLowerCase().trim(), mobile || null, passwordHash, hasPassword ? 1 : 0, req.user.id]
    );

    const distId = uuidv4();
    await conn.query(
      `INSERT INTO distributors (id, user_id, commission_rate, city, district, address, area_of_operation, super_distributor_id,
                                  pan_number, bank_account_holder, bank_name, bank_account_number, bank_ifsc)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [distId, userId, commission_rate || 10.0, city || null, district || sdDistrict, address || null, area_of_operation || null, req.user.id,
       pan_number || null, bank_account_holder || null, bank_name || null, bank_account_number || null, bank_ifsc || null]
    );

    await conn.commit();

    let message;
    if (hasPassword) {
      message = 'Distributor created. They can log in immediately.';
      sendDistributorCreatedEmail(email, name, {
        username: email.toLowerCase().trim(),
        password,
        loginUrl: req.headers.origin,
        relatedUserId: userId,
      }).catch(e => console.error('SD distributor welcome email failed:', e.message));
    } else {
      const emailResult = await createAndSendPasswordToken(
        { id: userId, name, email, role: 'distributor' },
        'setup',
        req.headers.origin,
        { role: 'distributor', username: email.toLowerCase().trim() }
      );
      if (!emailResult.success) console.error('Dist setup email failed:', emailResult.error);
      message = 'Distributor created. Password setup email sent.';
    }

    const [rows] = await pool.query(
      `SELECT d.*, u.name, u.email, u.mobile, u.is_active FROM distributors d JOIN users u ON u.id = d.user_id WHERE d.id = ?`,
      [distId]
    );
    res.status(201).json({ distributor: rows[0], message });
  } catch (err) {
    await conn.rollback();
    console.error('SD createMyDistributor error:', err.message);
    res.status(500).json({ error: 'Server error creating distributor' });
  } finally {
    conn.release();
  }
}

// GET /api/super-distributors/me/distributors/:id
async function getMyDistributor(req, res) {
  try {
    const sdId = req.user.id;
    const [rows] = await pool.query(
      `SELECT d.*, u.name, u.email, u.mobile, u.is_active
       FROM distributors d JOIN users u ON u.id = d.user_id
       WHERE d.id = ? AND d.super_distributor_id = ? AND d.deleted_at IS NULL`,
      [req.params.id, sdId]
    );
    if (rows.length === 0) return res.status(404).json({ error: 'Distributor not found' });

    const [schools] = await pool.query(
      `SELECT s.id, s.name, s.status, s.created_at,
              u.name as admin_name
       FROM schools s LEFT JOIN users u ON u.id = s.admin_user_id
       WHERE s.distributor_id = ? AND s.deleted_at IS NULL
       ORDER BY s.created_at DESC`,
      [req.params.id]
    );

    res.json({ distributor: rows[0], schools });
  } catch (err) {
    console.error('SD getMyDistributor error:', err.message);
    res.status(500).json({ error: 'Server error fetching distributor' });
  }
}

// PUT /api/super-distributors/me/distributors/:id
async function updateMyDistributor(req, res) {
  try {
    if (!(await isMyDistributor(req.user.id, req.params.id))) {
      return res.status(403).json({ error: 'Access denied' });
    }

    const { name, mobile, city, district, address, area_of_operation, commission_rate, is_active,
            pan_number, bank_account_holder, bank_name, bank_account_number, bank_ifsc } = req.body;
    const [distRows] = await pool.query('SELECT user_id FROM distributors WHERE id = ?', [req.params.id]);
    const userId = distRows[0].user_id;

    if (name !== undefined) await pool.query('UPDATE users SET name = ? WHERE id = ?', [name, userId]);
    if (mobile !== undefined) await pool.query('UPDATE users SET mobile = ? WHERE id = ?', [mobile, userId]);
    if (is_active !== undefined) await pool.query('UPDATE users SET is_active = ? WHERE id = ?', [is_active ? 1 : 0, userId]);

    const updates = [];
    const values = [];
    if (city !== undefined) { updates.push('city = ?'); values.push(city); }
    if (district !== undefined) { updates.push('district = ?'); values.push(district); }
    if (address !== undefined) { updates.push('address = ?'); values.push(address); }
    if (area_of_operation !== undefined) { updates.push('area_of_operation = ?'); values.push(area_of_operation); }
    if (commission_rate !== undefined) { updates.push('commission_rate = ?'); values.push(commission_rate); }
    if (pan_number !== undefined) { updates.push('pan_number = ?'); values.push(pan_number); }
    if (bank_account_holder !== undefined) { updates.push('bank_account_holder = ?'); values.push(bank_account_holder); }
    if (bank_name !== undefined) { updates.push('bank_name = ?'); values.push(bank_name); }
    if (bank_account_number !== undefined) { updates.push('bank_account_number = ?'); values.push(bank_account_number); }
    if (bank_ifsc !== undefined) { updates.push('bank_ifsc = ?'); values.push(bank_ifsc); }
    if (updates.length > 0) {
      values.push(req.params.id);
      await pool.query(`UPDATE distributors SET ${updates.join(', ')} WHERE id = ?`, values);
    }

    const [rows] = await pool.query(
      `SELECT d.*, u.name, u.email, u.mobile, u.is_active FROM distributors d JOIN users u ON u.id = d.user_id WHERE d.id = ?`,
      [req.params.id]
    );
    res.json({ distributor: rows[0] });
  } catch (err) {
    console.error('SD updateMyDistributor error:', err.message);
    res.status(500).json({ error: 'Server error updating distributor' });
  }
}

// PUT /api/super-distributors/me/distributors/:id/avatar
async function uploadMyDistributorAvatar(req, res) {
  try {
    if (!req.file) return res.status(400).json({ error: 'No image file provided' });
    if (!(await isMyDistributor(req.user.id, req.params.id))) {
      return res.status(403).json({ error: 'Access denied' });
    }
    const avatarUrl = req.file.path;
    await pool.query('UPDATE distributors SET avatar_url = ? WHERE id = ?', [avatarUrl, req.params.id]);
    res.json({ avatar_url: avatarUrl });
  } catch (err) {
    console.error('SD uploadMyDistributorAvatar error:', err.message);
    res.status(500).json({ error: 'Server error uploading profile photo' });
  }
}

// DELETE /api/super-distributors/me/distributors/:id
async function deleteMyDistributor(req, res) {
  try {
    if (!(await isMyDistributor(req.user.id, req.params.id))) {
      return res.status(403).json({ error: 'Access denied' });
    }
    const [distRows] = await pool.query('SELECT user_id FROM distributors WHERE id = ?', [req.params.id]);
    await pool.query('UPDATE distributors SET deleted_at = NOW() WHERE id = ?', [req.params.id]);
    await pool.query("UPDATE users SET deleted_at = NOW(), is_active = 0 WHERE id = ? AND role = 'distributor'", [distRows[0].user_id]);
    res.json({ message: 'Distributor deleted successfully' });
  } catch (err) {
    console.error('SD deleteMyDistributor error:', err.message);
    res.status(500).json({ error: 'Server error deleting distributor' });
  }
}

// GET /api/super-distributors/me/schools
async function listMySchools(req, res) {
  try {
    const { status } = req.query;
    const sdId = req.user.id;

    let query = `
      SELECT s.id, s.name, s.status, s.district, s.city, s.created_at,
             u.name as admin_name,
             du.name as distributor_name, du.mobile as distributor_phone
      FROM schools s
      LEFT JOIN users u ON u.id = s.admin_user_id
      LEFT JOIN distributors d ON d.id = s.distributor_id
      LEFT JOIN users du ON du.id = d.user_id
      WHERE s.deleted_at IS NULL
        AND (s.super_distributor_id = ? OR d.super_distributor_id = ?)`;
    const params = [sdId, sdId];
    if (status) { query += ' AND s.status = ?'; params.push(status); }
    query += ' ORDER BY s.created_at DESC';

    const [rows] = await pool.query(query, params);
    res.json({ schools: rows });
  } catch (err) {
    console.error('SD listMySchools error:', err.message);
    res.status(500).json({ error: 'Server error fetching schools' });
  }
}

// POST /api/super-distributors/me/schools
async function addMySchool(req, res) {
  const conn = await pool.getConnection();
  try {
    const sdId = req.user.id;
    const { name, adminName, adminEmail, adminMobile, udise_code, village, city, district, taluka, pin_code, phone, medium, board, distributorId,
             class_from, class_to, insideLat, insideLng, outsideLat, outsideLng } = req.body;

    if (!name || !adminName || !adminEmail) {
      return res.status(400).json({ error: 'School name, admin name, and admin email are required' });
    }

    // Geo-tagged inside/outside photos are mandatory for every new school —
    // enforced here (backend), not just hidden/disabled in the frontend.
    const insidePhotoFile = req.files?.insidePhoto?.[0];
    const outsidePhotoFile = req.files?.outsidePhoto?.[0];
    if (!insidePhotoFile) return res.status(400).json({ error: 'Please upload the geo-tagged inside photo of the school.' });
    if (!outsidePhotoFile) return res.status(400).json({ error: 'Please upload the geo-tagged outside photo of the school.' });
    if (!insideLat || !insideLng) return res.status(400).json({ error: 'Location was not captured for the inside photo. Please allow location access and retake the photo.' });
    if (!outsideLat || !outsideLng) return res.status(400).json({ error: 'Location was not captured for the outside photo. Please allow location access and retake the photo.' });

    // If a distributorId is given, verify it belongs to this SD
    if (distributorId) {
      const belongs = await isMyDistributor(sdId, distributorId);
      if (!belongs) return res.status(403).json({ error: 'That distributor does not belong to you' });
    }

    const [existing] = await conn.query('SELECT id FROM users WHERE email = ? AND deleted_at IS NULL', [adminEmail.toLowerCase().trim()]);
    if (existing.length > 0) return res.status(409).json({ error: 'A user with this email already exists' });

    await conn.beginTransaction();

    const userId = uuidv4();
    await conn.query(
      `INSERT INTO users (id, role, name, email, mobile, is_active, password_set, created_by) VALUES (?, 'schoolAdmin', ?, ?, ?, 1, 0, ?)`,
      [userId, adminName, adminEmail.toLowerCase().trim(), adminMobile || null, sdId]
    );

    const schoolId = uuidv4();
    const [countRows] = await conn.query('SELECT COUNT(*) as count FROM schools');
    const loginId = `SCH${String(Number(countRows[0].count) + 1).padStart(3, '0')}`;

    await conn.query(
      `INSERT INTO schools (id, admin_user_id, distributor_id, super_distributor_id, name, login_id, udise_code, village, city, district, taluka, pin_code, phone, email, medium, board, class_from, class_to, status,
              inside_photo_url, inside_photo_lat, inside_photo_lng, inside_photo_captured_at,
              outside_photo_url, outside_photo_lat, outside_photo_lng, outside_photo_captured_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?, ?, NOW(), ?, ?, ?, NOW())`,
      [schoolId, userId, distributorId || null, sdId, name, loginId, udise_code, village, city, district, taluka, pin_code, phone, adminEmail.toLowerCase().trim(), medium, board, class_from || null, class_to || null,
       insidePhotoFile.path, insideLat, insideLng, outsidePhotoFile.path, outsideLat, outsideLng]
    );

    await conn.query(`INSERT INTO wallets (id, school_id, balance) VALUES (?, ?, 0)`, [uuidv4(), schoolId]);

    await conn.commit();

    // Notify super admins
    const [superAdmins] = await pool.query("SELECT id FROM users WHERE role = 'superAdmin' AND is_active = 1");
    for (const admin of superAdmins) {
      await createNotification(admin.id, `New school "${name}" submitted by Super Distributor, awaiting approval.`);
    }

    res.status(201).json({ message: 'School submitted for approval.' });
  } catch (err) {
    await conn.rollback();
    console.error('SD addMySchool error:', err.message);
    res.status(500).json({ error: 'Server error adding school' });
  } finally {
    conn.release();
  }
}

// PUT /api/super-distributors/me/schools/:id
async function updateMySchool(req, res) {
  try {
    const mine = await isMySchool(req.user.id, req.params.id);
    if (!mine) return res.status(403).json({ error: 'Access denied' });

    const EDITABLE = ['name', 'udise_code', 'village', 'city', 'district', 'taluka', 'pin_code', 'phone', 'medium', 'board', 'class_from', 'class_to'];
    const updates = [];
    const values = [];
    EDITABLE.forEach(f => { if (req.body[f] !== undefined) { updates.push(`${f} = ?`); values.push(req.body[f]); } });
    if (updates.length === 0) return res.status(400).json({ error: 'No fields to update' });

    values.push(req.params.id);
    await pool.query(`UPDATE schools SET ${updates.join(', ')} WHERE id = ?`, values);

    const [rows] = await pool.query('SELECT * FROM schools WHERE id = ?', [req.params.id]);
    res.json({ school: stripSchoolBlobFields(rows[0]) });
  } catch (err) {
    console.error('SD updateMySchool error:', err.message);
    res.status(500).json({ error: 'Server error updating school' });
  }
}

// DELETE /api/super-distributors/me/schools/:id
async function deleteMySchool(req, res) {
  try {
    const mine = await isMySchool(req.user.id, req.params.id);
    if (!mine) return res.status(403).json({ error: 'Access denied' });

    const [rows] = await pool.query('SELECT * FROM schools WHERE id = ?', [req.params.id]);
    if (rows.length === 0) return res.status(404).json({ error: 'School not found' });
    if (rows[0].status !== 'pending') {
      return res.status(409).json({ error: 'Only pending schools can be withdrawn. Contact Super Admin.' });
    }

    const adminUserId = rows[0].admin_user_id;
    await pool.query('DELETE FROM schools WHERE id = ?', [req.params.id]);
    if (adminUserId) await pool.query("DELETE FROM users WHERE id = ? AND role = 'schoolAdmin'", [adminUserId]);

    res.json({ message: 'School withdrawn successfully' });
  } catch (err) {
    console.error('SD deleteMySchool error:', err.message);
    res.status(500).json({ error: 'Server error deleting school' });
  }
}

module.exports = {
  // SA
  listSuperDistributors, createSuperDistributor, updateSuperDistributorByAdmin, deleteSuperDistributor,
  uploadSuperDistributorAvatarByAdmin,
  // SD own
  getMyProfile, updateMyProfile, uploadMyAvatar, changeMyPassword, getDashboard,
  listMyDistributors, createMyDistributor, getMyDistributor, updateMyDistributor, deleteMyDistributor,
  uploadMyDistributorAvatar,
  listMySchools, addMySchool, updateMySchool, deleteMySchool
};
