const PDFDocument = require('pdfkit');
const fs = require('fs');

const NAVY = '#0F2A5E';
const GREY = '#6b7280';
const TEXT = '#1a1a1a';
const BORDER = '#e2e8f0';

function safe(v, fallback = '-') {
  return (v === null || v === undefined || v === '') ? fallback : String(v);
}

function fmtDate(d) {
  const dt = d ? new Date(d) : new Date();
  const dd = String(dt.getDate()).padStart(2, '0');
  const mm = String(dt.getMonth() + 1).padStart(2, '0');
  return `${dd}/${mm}/${dt.getFullYear()}`;
}

const TYPE_LABELS = { lc: 'Leaving Certificate', bonafide: 'Bonafide Certificate', idcard: 'Student ID Card', relation: 'Relation Certificate' };

// Generates a simple, self-contained receipt PDF — school + student +
// certificate identification and the final receipt amount only (no
// certificate-price line item; the receipt amount is the single number
// that matters to the school). No dependency on certificate PDF
// templates/borders on purpose: a receipt is an accounting document, not
// a certificate.
function generateReceiptPdf({
  school, student, certificate, receipt, generatedByName, outputPath,
}) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A5', margin: 40 });
      const stream = fs.createWriteStream(outputPath);
      doc.pipe(stream);

      const left = 40;
      const width = doc.page.width - 80;

      doc.font('Helvetica-Bold').fontSize(17).fillColor(NAVY)
        .text(safe(school.name, 'School'), left, 40, { width, align: 'center' });
      doc.font('Helvetica').fontSize(9).fillColor(GREY)
        .text([school.city, school.district].filter(Boolean).join(', ') || '-', { width, align: 'center' });

      let y = 86;
      doc.save().moveTo(left, y).lineTo(left + width, y).lineWidth(1.3).strokeColor(NAVY).stroke().restore();
      y += 16;

      doc.font('Helvetica-Bold').fontSize(13).fillColor(TEXT)
        .text('PAYMENT RECEIPT', left, y, { width, align: 'center' });
      y += 30;

      function row(label, value) {
        doc.font('Helvetica').fontSize(9.5).fillColor(GREY).text(label, left, y, { width: width * 0.45 });
        doc.font('Helvetica-Bold').fontSize(9.5).fillColor(TEXT)
          .text(safe(value), left + width * 0.45, y, { width: width * 0.55, align: 'right' });
        y += 20;
      }

      row('Receipt No.', receipt.receipt_number);
      row('Date', fmtDate(receipt.created_at));
      row('Student Name', student.full_name);
      row('Admission / Register No.', student.register_number);
      row('Certificate Type', TYPE_LABELS[certificate.type] || certificate.type);
      row('Certificate No.', certificate.serial_number);
      if (certificate.type === 'lc') {
        row('Copy Type', (receipt.certificate_variant || 'original').toUpperCase());
      }
      row('Generated By', generatedByName);
      row('Transaction Ref.', certificate.wallet_transaction_id);

      y += 10;
      doc.save().moveTo(left, y).lineTo(left + width, y).lineWidth(0.7).strokeColor(BORDER).stroke().restore();
      y += 20;

      doc.save();
      doc.roundedRect(left, y, width, 36, 5).fillColor(NAVY).fill();
      doc.restore();
      doc.font('Helvetica-Bold').fontSize(11).fillColor('#fff')
        .text('RECEIPT AMOUNT', left + 12, y + 12);
      doc.font('Helvetica-Bold').fontSize(15).fillColor('#fff')
        .text(`Rs. ${Number(receipt.receipt_amount).toFixed(2)}`, left, y + 10, { width: width - 12, align: 'right' });
      y += 56;

      doc.save().moveTo(left, y).lineTo(left + width, y).lineWidth(0.7).strokeColor(BORDER).stroke().restore();
      y += 14;

      doc.font('Helvetica-Oblique').fontSize(7.5).fillColor(GREY)
        .text('This is a system-generated receipt and does not require a signature.', left, y, { width, align: 'center' });
      y += 14;
      doc.font('Helvetica-Bold').fontSize(7.5).fillColor(NAVY)
        .text('Powered by One Click School Solutions', left, y, { width, align: 'center' });

      doc.end();
      stream.on('finish', () => resolve(outputPath));
      stream.on('error', reject);
    } catch (e) { reject(e); }
  });
}

module.exports = { generateReceiptPdf };
